server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  file:
    name: mylog.log
  level:
    root: ERROR




api:
  prefix: api

jwt:
  expiration: 36000
  secretKey: ${JWT_SECRET_KEY:}
google:
  client-id: ${KEY_GOOGLE:}
